const Article = () => (
  <div>
    <h1>This is a sample article</h1>
    <img src="https://cdn.pixabay.com/photo/2016/09/21/04/46/barley-field-1684052_1280.jpg"/>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Purus non enim praesent elementum facilisis leo vel. Sodales ut eu sem integer vitae justo. Duis ultricies lacus sed turpis tincidunt id. Non arcu risus quis varius quam. Etiam non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Feugiat vivamus at augue eget arcu. Aliquet porttitor lacus luctus accumsan tortor posuere ac ut consequat. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Varius duis at consectetur lorem donec massa sapien faucibus et. Consequat nisl vel pretium lectus. Vitae suscipit tellus mauris a. Mauris nunc congue nisi vitae suscipit.</p>
    <p>Lobortis mattis aliquam faucibus purus. Sollicitudin tempor id eu nisl. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Vitae congue eu consequat ac felis donec et odio. Neque convallis a cras semper. Morbi tempus iaculis urna id volutpat. Dictum at tempor commodo ullamcorper. Tincidunt arcu non sodales neque sodales. Neque vitae tempus quam pellentesque. Ac felis donec et odio pellentesque diam. In ornare quam viverra orci sagittis. Orci nulla pellentesque dignissim enim. Nec nam aliquam sem et tortor. Sit amet nulla facilisi morbi. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut.</p>
    <p>Blandit aliquam etiam erat velit scelerisque in. Eget mi proin sed libero enim sed faucibus turpis. Sed tempus urna et pharetra pharetra massa massa ultricies mi. Mollis nunc sed id semper risus in hendrerit. Eget lorem dolor sed viverra ipsum nunc. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Bibendum enim facilisis gravida neque convallis a cras. Elit pellentesque habitant morbi tristique senectus et netus. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Quam adipiscing vitae proin sagittis nisl rhoncus. Augue eget arcu dictum varius duis at consectetur lorem donec. Arcu ac tortor dignissim convallis aenean et tortor at risus. Cursus eget nunc scelerisque viverra mauris. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Urna et pharetra pharetra massa.</p>
    <p>Ut sem viverra aliquet eget sit amet tellus. In fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Neque vitae tempus quam pellentesque nec nam aliquam. Facilisis gravida neque convallis a. Consectetur a erat nam at lectus urna duis convallis. Felis bibendum ut tristique et. Est lorem ipsum dolor sit amet consectetur adipiscing elit. Velit dignissim sodales ut eu sem integer vitae justo. Varius sit amet mattis vulputate. Et malesuada fames ac turpis. Lobortis scelerisque fermentum dui faucibus in ornare quam. Enim sed faucibus turpis in eu mi bibendum neque egestas. Venenatis urna cursus eget nunc scelerisque viverra mauris in. Tristique et egestas quis ipsum. Ut diam quam nulla porttitor massa id neque aliquam. Arcu dictum varius duis at. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Blandit cursus risus at ultrices mi tempus imperdiet.</p>
    <p>Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Iaculis nunc sed augue lacus viverra vitae congue eu consequat. Hac habitasse platea dictumst quisque sagittis purus sit amet volutpat. Aliquam sem et tortor consequat. Vitae proin sagittis nisl rhoncus mattis. Augue lacus viverra vitae congue eu consequat. Vel facilisis volutpat est velit egestas dui id ornare. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Purus gravida quis blandit turpis cursus in hac habitasse platea. Tellus in metus vulputate eu scelerisque. Ornare suspendisse sed nisi lacus. Eu feugiat pretium nibh ipsum consequat. Eget egestas purus viverra accumsan in nisl nisi scelerisque eu. Eget egestas purus viverra accumsan in. Nibh nisl condimentum id venenatis a condimentum vitae. In nibh mauris cursus mattis molestie a. Tortor at risus viverra adipiscing at in. Sapien eget mi proin sed libero enim.</p>
  </div>
);

export default Article;
